<%
  file  = File.join(ENV['HOME'], 'etc', 'assda', 'dbconfig.yml')
  @conf = File.exist?(file) && YAML::load(File.open(file))['production'] || {}
%>
template: &template
  adapter:  <%= defined?(JRUBY_VERSION) ? 'jdbcmysql' : 'mysql2' %>
  pool:     5
  timeout:  5000
  database: <%= @conf['database'] %>
  host:     <%= @conf['host'] %>
  username: <%= @conf['username'] %>
  password: <%= @conf['password'] %>

production:
  <<: *template

development:
  <<: *template
