<%
  require 'java' if defined?(JRUBY_VERSION)

  file = ENV['OID_DBCONFIG'] ||
    ( defined?(JRUBY_VERSION) && java.lang.System.getProperty('oid.dbconfig')) ||
    ( defined?(JRUBY_VERSION) && defined?($servlet_context) &&
      $servlet_context.get_init_parameter('oid.dbconfig') ) ||
    File.join(ENV['HOME'], 'etc', 'assda', 'dbconfig.yml')

  @conf = File.exist?(file) && YAML::load(File.open(file)) || {}
  # Fix behaviour of "rails db development_logs"
  rails_env = Rails.env.gsub('_logs', '')
%>
template: &template
  adapter:  <%= (defined?(JRUBY_VERSION) && @conf[rails_env]['jdbc']) || @conf[rails_env]['adapter'] %>
  pool:     5
  timeout:  5000
  database: <%= @conf[rails_env]['database'] %>
  host:     <%= @conf[rails_env]['host'] %>
  username: <%= @conf[rails_env]['username'] %>
  password: <%= @conf[rails_env]['password'] %>

production:
  <<: *template

production_logs:
  <<: *template
  database: <%= @conf[rails_env+'_logs']['database'] %>
  username: <%= @conf[rails_env+'_logs']['username'] %>
  
development:
  <<: *template

development_logs:
  <<: *template
  database: <%= @conf[rails_env+'_logs']['database'] %>

test:
  <<: *template

test_logs:
  <<: *template
  database: <%= @conf[rails_env+'_logs']['database'] %>
