production: &production
  adapter: mysql2
  database: security
  host: <%= Secrets::DATABASE_HOST %>
  username: <%= Secrets::DATABASE_USERNAME %>
  password: <%= Secrets::DATABASE_PASSWORD %>

production_logs:
  <<: *production
  database: logs


development:
  adapter: sqlite3
  database: 'db/dev.db'

development_logs:
  adapter: sqlite3
  database: 'db/dev_logs.db'


test:
  adapter: sqlite3
  database: 'db/test.db'

test_logs:
  adapter: sqlite3
  database: 'db/test_logs.db'
