production: &production
  adapter: mysql2
  database: security
  host: <%= Secrets::DATABASE_HOST %>
  username: <%= Secrets::DATABASE_USERNAME %>
  password: <%= Secrets::DATABASE_PASSWORD %>

production_logs:
  <<: *production
  database: logs

production_nesstar:
  <<: *production
  database: nesstar


staff:
  adapter: sqlite3
  database: 'db/prod.db'

staff_logs:
  adapter: sqlite3
  database: 'db/prod_logs.db'

staff_nesstar:
  adapter: sqlite3
  database: 'db/prod_nesstar.db'


development:
  adapter: sqlite3
  database: 'db/dev.db'

development_logs:
  adapter: sqlite3
  database: 'db/dev_logs.db'

development_nesstar:
  adapter: sqlite3
  database: 'db/dev_nesstar.db'


test:
  adapter: sqlite3
  database: 'db/test.db'

test_logs:
  adapter: sqlite3
  database: 'db/test_logs.db'

test_nesstar:
  adapter: sqlite3
  database: 'db/test_nesstar.db'
