production: &production
  adapter: mysql2
  database: security
  host: <%= Secrets::DATABASE_HOST %>
  username: <%= Secrets::DATABASE_USERNAME %>
  password: <%= Secrets::DATABASE_PASSWORD %>

production_logs:
  <<: *production
  database: logs

production_nesstar:
  <<: *production
  database: nesstar


staff:
  <<: *production
  database: security

staff_logs:
  <<: *production
  database: logs

staff_nesstar:
  <<: *production
  database: nesstar


devs:
  adapter: sqlite3
  database: 'db/prod.db'

devs_logs:
  adapter: sqlite3
  database: 'db/prod_logs.db'

devs_nesstar:
  adapter: sqlite3
  database: 'db/prod_nesstar.db'

<% if ENV['use_mysql'].blank? %>

development:
  adapter: sqlite3
  database: 'db/dev.db'

development_logs:
  adapter: sqlite3
  database: 'db/dev_logs.db'

development_nesstar:
  adapter: sqlite3
  database: 'db/dev_nesstar.db'

test:
  adapter: sqlite3
  database: 'db/test.db'

test_logs:
  adapter: sqlite3
  database: 'db/test_logs.db'

test_nesstar:
  adapter: sqlite3
  database: 'db/test_nesstar.db'

<% else %>

development_base: &development_local
  adapter: mysql2
  username: <%= Secrets::LOCAL_DATABASE_USERNAME %>
  password: <%= Secrets::LOCAL_DATABASE_PASSWORD %>

development:
  <<: *development_local
  database: adausers_dev

development_logs:
  <<: *development_local
  database: adausers_dev_logs

development_nesstar:
  <<: *development_local
  database: adausers_dev_nesstar

test:
  <<: *development_local
  database: adausers_test

test_logs:
  <<: *development_local
  database: adausers_test_logs

test_nesstar:
  <<: *development_local
  database: adausers_test_nesstar

<% end %>
